spring:
  application:
    name: gym-back
  threads:
    virtual:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/gym?queryInterceptors=brave.mysql8.TracingQueryInterceptor
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  tracing:
    sampling:
      probability: 0.1