spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        query:
          fail_on_pagination_over_collection_fetch: true
  datasource:
    url: jdbc:mysql://localhost:3306/gym
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: gym-back-app
  threads:
    virtual:
      enabled: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: gym-back-worker
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'

management:
  endpoints:
    web:
      exposure:
        include: ["prometheus"]
  tracing:
    sampling:
      probability: 1

logging:
  pattern:
  level:
    org.hibernate.orm.jdbc.bind: trace

