version: '3.8'
services:

  metabase:
    image: metabase/metabase
    container_name: metabase
    hostname: metabase
    environment:
      MB_DB_TYPE: mysql
      MB_DB_CONNECTION_URI: jdbc:mysql://mysql:3306/metabase?user=root&password=root
    ports:
      - '3004:3000'
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.31
    container_name: mysql
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gym
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - '3306:3306'

  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - '9411:9411'

  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    network_mode: host
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

volumes:
  mysql_volume:
  mongo_volume: