spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: gym-back
  threads:
    virtual:
      enabled: true
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        query:
          fail_on_pagination_over_collection_fetch: true
  datasource:
    url: jdbc:mysql://localhost:3306/gym?queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    consumer:
      group-id: group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'


management:
  endpoints:
    web:
      exposure:
        include: ["prometheus"]
  tracing:
    sampling:
      probability: 0.1

logging:
  pattern:
  level:
    org.hibernate.orm.jdbc.bind: trace